name: Release
on:
  release:
    types: [created]
jobs:
  manual_process:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish To npm
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
